# Generated by Django 3.2.13 on 2022-08-02 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^\\w+( \\w+)*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
